name: Daily Data Update 

on: workflow_dispatch

jobs: 
  update-data:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
      FRED_KEY: ${{secrets.FRED_KEY}}
      GT_KEY: ${{secrets.GT_KEY}}
      BLS_KEY: ${{secrets.BLS_KEY}}
      RENV_PATHS_ROOT: ~/renv

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v4
        with:
          r-version: "4.4.2"

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("reticulate"))'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.6' # or whatever version you need

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client json pandas pprint datetime dill pathlib # or other packages needed by your script

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Generate Data
        run: |
          source("Do/master.R")
        shell: Rscript {0}

      - name: Commit New Data Files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -am "GitHub Action - Daily Data Update - $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
